# Generated by Django 3.2.9 on 2021-11-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cast',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Movie Description')),
                ('language', models.CharField(max_length=25)),
                ('running_time', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/%y/%m/%d')),
                ('active', models.BooleanField(default=False)),
                ('rate', models.IntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('cast', models.ManyToManyField(to='movie.Cast')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.category')),
            ],
            options={
                'verbose_name': 'movie',
                'ordering': ['id'],
            },
        ),
    ]
